### ISSUE TITLE
Please remove styled-components dependency for performance

### ISSUE THREAD

**Issue by RobbieGM** [thegrinder/rr-notifications#5]
According to [BundlePhobia](https://bundlephobia.com/result?p=styled-components@5.1.0), the `styled-components` module could cause a page load time increase of 0.25 seconds on slow connections. This performance hit is undesirable and easily fixable, considering that your project only use the module twice and in each case it would be easy to use vanilla React/CSS instead. Could you consider making this improvement? Alternatively, I could open a PR and do it.
Thanks!

**Comment by thegrinder** [comment]
I created it with `styled-components` as I use them in almost all of my projects. However, you're right, it is probably unnecessary here. I think an api similar to what you find in `react-modal` (i.e. `--after-open`, `--open` class names) would be perfect. Feel free to open the PR 👍
