### ISSUE TITLE
rr-notifications doesn't work in SSR/Node environment

### ISSUE THREAD

**Issue by RobbieGM** [thegrinder/rr-notifications#6]
When importing `rr-notifications` in Next.js, an error is thrown saying that `window is not defined`. This is understandable given that webpack uses the `window` constant unconditionally in the output `index.js` file. This behavior should be easy to change, luckily. According to [this issue](https://github.com/webpack/webpack/issues/6522), all that needs to be changed is the `webpack.config.js` file, where you should add `globalObject: "this"` in the config object. I'd be willing to create a PR to fix this if you don't want to do it, though it should be a  fairly simple fix.
Thanks!

**Comment by thegrinder** [comment]
Thank you for creating the issue. I haven't updated the package in a while, feel free to open the PR 👍
